-- Owner decision F36 (2026-09-27), beyond FR-124: support requests become
-- numbered tickets worked from the operators' Telegram chat, and their
-- messages are kept so the console (and later the site) can show them.
-- A customer has at most one live ticket (`ux_support_tickets_live_p`), so
-- two messages arriving together cannot open two.
-- reversible: yes — DROP TABLE support_faq, support_templates, support_topics,
-- support_messages, support_tickets; DROP TYPE support_message_direction,
-- support_closed_by, support_ticket_channel, support_ticket_status.
CREATE TYPE support_ticket_status AS ENUM ('open', 'in_progress', 'closed');
CREATE TYPE support_ticket_channel AS ENUM ('shop', 'support', 'web');
CREATE TYPE support_closed_by AS ENUM ('operator', 'customer', 'auto');
CREATE TYPE support_message_direction AS ENUM ('customer', 'operator', 'note', 'system');

CREATE TABLE support_tickets (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  user_id uuid NOT NULL REFERENCES users(id),
  channel support_ticket_channel NOT NULL,
  status support_ticket_status NOT NULL DEFAULT 'open',
  opened_by text NOT NULL DEFAULT 'customer' CHECK (opened_by IN ('customer', 'operator')),
  assignee_telegram_id bigint,
  assignee_name text,
  taken_at timestamptz,
  first_response_at timestamptz,
  last_customer_at timestamptz,
  last_operator_at timestamptz,
  reminded_at timestamptz,
  closed_at timestamptz,
  closed_by support_closed_by,
  closed_silently boolean NOT NULL DEFAULT false,
  rating smallint CHECK (rating BETWEEN 1 AND 5),
  rated_at timestamptz,
  chat_id bigint,
  thread_id integer,
  card_message_id integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_support_tickets_live_p ON support_tickets(user_id) WHERE status <> 'closed';
CREATE INDEX ix_support_tickets_status_created ON support_tickets(status, created_at);
CREATE INDEX ix_support_tickets_user_created ON support_tickets(user_id, created_at DESC);

CREATE TABLE support_messages (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  ticket_id uuid NOT NULL REFERENCES support_tickets(id),
  direction support_message_direction NOT NULL,
  author_telegram_id bigint,
  author_name text,
  kind text NOT NULL,
  text text,
  file_id text,
  file_unique_id text,
  customer_message_id integer,
  operator_chat_id bigint,
  operator_message_id integer,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_support_messages_ticket_created ON support_messages(ticket_id, created_at);
CREATE INDEX ix_support_messages_operator_message
  ON support_messages(operator_chat_id, operator_message_id) WHERE operator_message_id IS NOT NULL;

CREATE TABLE support_topics (
  chat_id bigint NOT NULL,
  user_id uuid NOT NULL REFERENCES users(id),
  thread_id integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (chat_id, user_id),
  UNIQUE (chat_id, thread_id)
);

CREATE TABLE support_templates (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  code text NOT NULL UNIQUE CHECK (code ~ '^[a-z0-9_-]{1,32}$'),
  title text NOT NULL,
  body jsonb NOT NULL,
  sort_order integer NOT NULL DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE support_faq (
  id uuid PRIMARY KEY DEFAULT uuidv7(),
  question jsonb NOT NULL,
  answer jsonb NOT NULL,
  sort_order integer NOT NULL DEFAULT 100,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
